set echo on
set feedback on
set lines 136
set pages 1000
set timing on

spool change_archivelog_mode.log

conn / as sysdba

SHUTDOWN immediate
STARTUP MOUNT
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE = 100G;
[oracle@yns-tokyo ~]$
[oracle@yns-tokyo ~]$ cat create_atlassian.sql
set echo on
set feedback on
set lines 136
set pages 1000
set timing on

spool create_atlassian.log

conn / as sysdba

--
-- create tablespaces
--
CREATE TABLESPACE JIRA
DATAFILE '/DATA/oradata/XE/jira01.dbf'
SIZE 50m AUTOEXTEND ON LOGGING
ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO ;

CREATE TABLESPACE CONF
DATAFILE '/DATA/oradata/XE/conf01.dbf'
SIZE 50m AUTOEXTEND ON LOGGING
ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO ;

CREATE TABLESPACE STASH
DATAFILE '/DATA/oradata/XE/stash01.dbf'
SIZE 50m AUTOEXTEND ON LOGGING
ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO ;

CREATE TABLESPACE FISHEYE
DATAFILE '/DATA/oradata/XE/fisheye01.dbf'
SIZE 50m AUTOEXTEND ON LOGGING
ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO ;

CREATE TABLESPACE BAMBOO
DATAFILE '/DATA/oradata/XE/bamboo01.dbf'
SIZE 50m AUTOEXTEND ON LOGGING
ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO ;


CREATE TABLESPACE CROWD
DATAFILE '/DATA/oradata/XE/crowd01.dbf'
SIZE 50m AUTOEXTEND ON LOGGING
ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO ;

CREATE TABLESPACE CROWDID
DATAFILE '/DATA/oradata/XE/crowdid01.dbf'
SIZE 50m AUTOEXTEND ON LOGGING
ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO ;

-- User [JIRA]
--

CREATE USER JIRA identified by "jira123!"
DEFAULT TABLESPACE JIRA
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK ;

GRANT CONNECT TO JIRA ;
GRANT CREATE SEQUENCE TO JIRA ;
GRANT CREATE TABLE TO JIRA ;
GRANT CREATE TRIGGER TO JIRA ;
GRANT EXECUTE_CATALOG_ROLE TO JIRA ;
GRANT RESOURCE TO JIRA ;
GRANT SELECT_CATALOG_ROLE TO JIRA ;
GRANT UNLIMITED TABLESPACE TO JIRA ;


-- User [CONF]
CREATE USER CONF identified by "conf123!"
DEFAULT TABLESPACE CONF
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK ;

GRANT CONNECT TO CONF ;
GRANT CREATE SEQUENCE TO CONF ;
GRANT CREATE TABLE TO CONF ;
GRANT CREATE TRIGGER TO CONF ;
GRANT EXECUTE_CATALOG_ROLE TO CONF ;
GRANT RESOURCE TO CONF ;
GRANT UNLIMITED TABLESPACE TO CONF ;
GRANT UNLIMITED TABLESPACE TO CONF ;

-- User [STASH]
CREATE USER STASH identified by "stash123!"
DEFAULT TABLESPACE STASH
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK ;

GRANT CONNECT TO STASH ;
GRANT CREATE SEQUENCE TO STASH ;
GRANT CREATE TABLE TO STASH ;
GRANT CREATE TRIGGER TO STASH ;
GRANT EXECUTE_CATALOG_ROLE TO STASH ;
GRANT RESOURCE TO STASH ;
GRANT UNLIMITED TABLESPACE TO STASH ;
GRANT UNLIMITED TABLESPACE TO STASH ;

-- User [FISHEYE]
CREATE USER FISHEYE identified by "fisheye123!"
DEFAULT TABLESPACE FISHEYE
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK ;

GRANT CONNECT TO FISHEYE;
GRANT CREATE SEQUENCE TO FISHEYE;
GRANT CREATE TABLE TO FISHEYE;
GRANT CREATE TRIGGER TO FISHEYE;
GRANT EXECUTE_CATALOG_ROLE TO FISHEYE;
GRANT RESOURCE TO FISHEYE;
GRANT UNLIMITED TABLESPACE TO FISHEYE;
GRANT UNLIMITED TABLESPACE TO FISHEYE;

-- User [BAMBOO]
CREATE USER BAMBOO identified by "bamboo123!"
DEFAULT TABLESPACE BAMBOO
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK ;

GRANT CONNECT TO BAMBOO;
GRANT CREATE SEQUENCE TO BAMBOO;
GRANT CREATE TABLE TO BAMBOO;
GRANT CREATE TRIGGER TO BAMBOO;
GRANT EXECUTE_CATALOG_ROLE TO BAMBOO;
GRANT RESOURCE TO BAMBOO;
GRANT UNLIMITED TABLESPACE TO BAMBOO;
GRANT UNLIMITED TABLESPACE TO BAMBOO;

-- User [CROWD]
CREATE USER CROWD identified by "crowd123!"
DEFAULT TABLESPACE CROWD
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK ;

GRANT CONNECT TO CROWD;
GRANT CREATE SEQUENCE TO CROWD;
GRANT CREATE TABLE TO CROWD;
GRANT CREATE TRIGGER TO CROWD;
GRANT EXECUTE_CATALOG_ROLE TO CROWD;
GRANT RESOURCE TO CROWD;
GRANT UNLIMITED TABLESPACE TO CROWD;
GRANT UNLIMITED TABLESPACE TO CROWD;


-- User [CROWDID]
CREATE USER CROWDID identified by "crowdid123!"
DEFAULT TABLESPACE CROWDID
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK ;

GRANT CONNECT TO CROWDID;
GRANT CREATE SEQUENCE TO CROWDID;
GRANT CREATE TABLE TO CROWDID;
GRANT CREATE TRIGGER TO CROWDID;
GRANT EXECUTE_CATALOG_ROLE TO CROWDID;
GRANT RESOURCE TO CROWDID;
GRANT UNLIMITED TABLESPACE TO CROWDID;
GRANT UNLIMITED TABLESPACE TO CROWDID;