#!/bin/bash

./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150804_0400-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150804_0800-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150804_1200-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150804_1600-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150804_2000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150805_0000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150805_0400-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150805_0800-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150805_1200-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150805_1600-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150805_2000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150806_0601-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150806_0800-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150806_1200-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150806_1600-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150806_2000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150807_0000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150807_0400-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150807_0800-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150807_1200-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150807_1600-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150807_2000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150808_0000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150808_0400-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150808_0800-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150808_1200-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150808_1600-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150808_2000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150809_0000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150809_0400-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150809_0800-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150809_1200-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150809_1600-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150809_2000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150810_0000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150810_0400-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150810_0800-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150810_1200-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150810_1600-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150810_2000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150811_0000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150811_0400-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150811_0800-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150811_1200-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150811_1600-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150811_2000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150812_0000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150812_0400-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150812_0800-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150812_1200-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150812_1600-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150812_2000-4h.nmon
./nmon-upldr.sh nmonlog upload /DATA/nmon-capture/yns-tokyo.ynsfuture.com/yns-tokyo.ynsfuture.com_150813_0000-4h.nmon
